### PR TITLE
Remove bad entry

### PR DESCRIPTION
**Pull request by dhirschfeld**
(try to reset the bot)

### CODE REVIEW

**Comment by CJ-Wright** [comment]
I'll merge in the morning

**Comment by dhirschfeld** [comment]
Thanks for taking a look!

**Comment by dhirschfeld** [comment]
No idea if this is correct so feel free to push any changes...

**Comment by CJ-Wright** [comment]
I think this PR will fix things https://github.com/regro/cf-scripts/pull/1073

**Comment by dhirschfeld** [comment]
Great, thanks @CJ-Wright! 👍 

I'll go ahead and close this then...

**Pull request closed without merging**
