### PR TITLE
Reset pythran resolution failure in 3.10 migration

### PR DESCRIPTION
**Pull request by h-vetinari**
Pythran failed to resolve (presumably before the numpy builds got added to the migrator itself by https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2096), and the bot just points to a two-day old resolution failure (and I couldn't find pythran being handled at all in a more recent bot-run, e.g. [here](https://github.com/regro/autotick-bot/runs/4101971181)).

I'm sure the bot will retry eventually, but given how many packages are still in the queue, I'd like to unlock the scipy-branch of the graph for the migration.

CC @beckermr @chrisburr @isuruf

### CODE REVIEW

**Comment by beckermr** [comment]
The bot should retry without this change. I will leave this PR open just in case but we should wait.

**Comment by h-vetinari** [comment]
I know the bot will try eventually, but what timeframe are we talking about? From your comment [here](https://github.com/regro/cf-scripts/issues/1468#issuecomment-952296640), it sounds like it would first go through the 800+ pending PRs before retrying pythran, which is going to be days if not weeks. I don't see the risk of merging this (though happy to be corrected), but a lot of benefit for not bottlenecking everything that depends on scipy.

**Comment by beckermr** [comment]
Yes, it will likely be a few weeks until it gets retried. Unblocking scipy a few weeks sooner doesn't actually matter on the scale of this migration. OTOH I don't see the harm in merging this. 

I saw a thumbs down from @isuruf. If he is ok with this getting merged, I am happy to go ahead.

**Comment by isuruf** [comment]
I'm still wondering what the rush here is. I've asked in multiple issues from @h-vetinari, but I haven't got any straight answer.
Pushing maintainers like this is a sure way of burning out people.

**Comment by isuruf** [comment]
The queue will get sorted in ~3 days

**Comment by isuruf** [comment]
Btw, I'm not opposed to merging this at all. @beckermr, it's totally up to you.

**Comment by beckermr** [comment]
Thanks @isuruf. Setting aside the other issues, this PR should be fine so I will merge it.

**Comment by h-vetinari** [comment]
> 
> 
> I'm still wondering what the rush here is. I've asked in multiple issues from @h-vetinari, but I haven't got any straight answer. Pushing maintainers like this is a sure way of burning out people.

Just to clarify, I'm not trying to be a burden to anyone, but rather doing the work myself (e.g. this PR, fixing others) to the degree that I can - and I've offered to shepherd the migration PRs.

The "rush" is that I think leaving delaying downstream of scipy by a few weeks leads to a substantially worse usage experience. There are many arguments that mitigate this, but again, I'm trying to do the work myself rather than asking for anything (with the obvious exception o pushing the merge button).

**Comment by h-vetinari** [comment]
Still, let me apologise if this is seen as stressing people out. I try to be cautious (and definitely not incessant) in my pings - generally once for where I think people should be aware. Happy to hear feedback how I can continue to contribute on the migration and other topics without coming across as pushy.

**Pull request merged**
